import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from 'next/image'
import Link from "next/link";
import { api } from "~/utils/api";
import Layout from '../components/Layout'
import Televisor from '../img/televisor.png'

import { register } from 'swiper/element/bundle'
import { useEffect, useState } from "react";
register();


export default function Home() {


  const [date,setDate]=useState(0)
  const [minutes,setMinutes]=useState(0)
  const [seconds,setSeconds]=useState(0)
  const interval = useEffect(()=>{
    setInterval(()=>{
      const date=new Date()
      setDate(24 - date.getHours())
      setMinutes(60 - date.getMinutes())
      setSeconds(( date.getSeconds()))
      
    },1000)
  },[]);


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div>
        </div>
        <div className='font-basic flex gap-[42px]'>
          <div className='flex flex-col items-center max-w-[570px] border-base border-solid border-[1px] rounded-lg shadow py-6 text-center'>
            <p className='text-3xl'>Горячие скидки</p>
            <hr className='w-[300px] h-[7px] rounded bg-base my-2' />
            <div className='max-w-[570px] ' >


              <swiper-container
                slides-per-view="1"
                navigation="true"
                pagination='true'
                loop='true'
              >
                <swiper-slide><Image src={Televisor} width={200} quality={100} height={200}/></swiper-slide>
                <swiper-slide><Image src={Televisor} width={200} height={200}/></swiper-slide>
                <swiper-slide><Image src={Televisor} width={200} height={200}/></swiper-slide>
                <swiper-slide><Image src={Televisor} width={200} height={200}/></swiper-slide>
                <swiper-slide><Image src={Televisor} width={200} height={200}/></swiper-slide>
                <swiper-slide><Image src={Televisor} width={200} height={200}/></swiper-slide>
                
              </swiper-container>
            </div>
          </div>
          <div className='flex flex-col items-center max-w-[570px] border-base border-solid border-[1px] rounded-lg shadow py-6 text-center'>
            <div className="flex w-full px-10 justify-between ">
              <p className='text-3xl'>
                Товар дня {" "}
            <hr className='w-[200px] h-[7px] rounded bg-base my-2' />
              </p>
              <p className='text-3xl'>
                {date}{":"}{minutes}{":"}{seconds}
              </p>
            </div>
            <div className='max-w-[570px] ' >
              <swiper-container
                slides-per-view="1"
                navigation="true"
                pagination='true'
                loop='true'
              >
                <swiper-slide><Image src={Televisor} width={200} quality={100} height={200}/></swiper-slide>
                <swiper-slide><Image src={Televisor} width={200} height={200}/></swiper-slide>
                <swiper-slide><Image src={Televisor} width={200} height={200}/></swiper-slide>
                <swiper-slide><Image src={Televisor} width={200} height={200}/></swiper-slide>
                <swiper-slide><Image src={Televisor} width={200} height={200}/></swiper-slide>
                <swiper-slide><Image src={Televisor} width={200} height={200}/></swiper-slide>
                
              </swiper-container>
            </div>
          </div>
        </div>

        <h1>Hello</h1>

        <div>
          <Content/>
        </div>
      </Layout>
    </>
  );

  }

const Content:React.FC=()=>
{
  const {data:posts}=api.posts.getAll.useQuery(
    undefined
  )
  return(
    <div>
    <div>{JSON.stringify(posts)}</div>
    </div>
  )
}
