import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from 'next/image'
import Link from "next/link";
import { api } from "~/utils/api";
import Layout from '../components/Layout'
import Televisor from '../img/televisor.png'

import { useEffect, useState } from "react";
import { title } from "process";


export default function Home() {
  const [data, setData] = useState(0)
  const [minutes, setMinutes] = useState(0)
  const [seconds, setSeconds] = useState(0)

  useEffect(() => {
    const interval = setInterval(() => {
      const date = new Date()
      setData(24 - date.getHours())
      setMinutes(60 - date.getMinutes())
      setSeconds(60 -(date.getSeconds()))

    }, 1000);
    return () => clearInterval(interval);
  }, []);


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
      <div className="max-w-[1180px] mx-auto">
        <div className='font-basic flex gap-[42px]'>
          <div className='flex flex-col items-center max-w-[570px] border-base border-solid border-[1px] rounded-lg shadow py-6 text-center'>
            <p className='text-3xl'>Горячие скидки</p>
            <hr className='w-[300px] h-[7px] rounded bg-base my-2' />
            <div className='max-w-[570px] ' >


              <swiper-container
                slides-per-view="1"
                navigation="true"
                pagination='true'
                loop='true'
              >
                <swiper-slide><Image src={Televisor} width={200} quality={100} height={200} /></swiper-slide>
                <swiper-slide><Image src={Televisor} width={200} height={200} /></swiper-slide>
                <swiper-slide><Image src={Televisor} width={200} height={200} /></swiper-slide>
                <swiper-slide><Image src={Televisor} width={200} height={200} /></swiper-slide>
                <swiper-slide><Image src={Televisor} width={200} height={200} /></swiper-slide>
                <swiper-slide><Image src={Televisor} width={200} height={200} /></swiper-slide>

              </swiper-container>
            </div>
          </div>
          <div className='flex flex-col items-center max-w-[570px] border-base border-solid border-[1px] rounded-lg shadow py-6 text-center'>
            <div className="flex w-full px-10 justify-between ">
              <div>
              <p className='text-3xl'>
                Товар дня
              </p>
                <hr className='w-[200px] h-[7px] rounded bg-base my-2' />
                </div>
              <p className='text-3xl'>
                {data}{":"}{minutes}{":"}{seconds}
              </p>
            </div>
            <div className='max-w-[570px] ' >
              <swiper-container
                slides-per-view="1"
                navigation="true"
                pagination='true'
                loop='true'
              >
                <swiper-slide><Image src={Televisor} width={200} quality={100} height={200} /></swiper-slide>
                <swiper-slide><Image src={Televisor} width={200} height={200} /></swiper-slide>
                <swiper-slide><Image src={Televisor} width={200} height={200} /></swiper-slide>
                <swiper-slide><Image src={Televisor} width={200} height={200} /></swiper-slide>
                <swiper-slide><Image src={Televisor} width={200} height={200} /></swiper-slide>
                <swiper-slide><Image src={Televisor} width={200} height={200} /></swiper-slide>

              </swiper-container>
            </div>
          </div>
        </div>
      </div>

        <div className="bg-base-opacity mx-auto m-[40px]">
            <div className="mx-auto max-w-[1180px]  py-[30px]">
              <p className='text-3xl'>Хиты продаж</p>
              <hr className='w-[300px] h-[7px] rounded bg-base my-2' />
              <Content />
            </div>
        </div>
      </Layout>
    </>
  );

}

const Content = () => {
  const { data: posts } = api.posts.getAll.useQuery()

  return (<>
    <ul className="grid grid-cols-4 justify-between gap-[10px] ">
    {posts?.map((item)=>
      <li key={item.id}
      className="flex flex-col justify-between border-solid bg-white border-[1px] text-center border-basic p-4 pb-2 rounded"
      >
      {item.title}
        <div className="flex mt-6 w-full justify-between">
          <p className="font-basic font-xl font-normal ">{item.price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, " ")}</p>
          <div className="flex gap-5">
            <button className="bg-red-600 p-1 rounded">К</button>
            <button>Л</button>
            <button>С</button>
          </div>
        </div>
      </li>
      )}
    </ul>
  </>)
}
